apiVersion: apps/v1
kind: Deployment
metadata:
  name: will42
  namespace: dev
spec:
    selector:
      matchLabels:
        app: will_app
    template:
      metadata:
        labels:
          app: will_app
      spec:
        containers:
        - name: will
          image: wil42/playground
          ports:
            - containerPort: 8888