apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-playground
  namespace: dev
spec:
    selector:
      matchLabels:
        app: will_app
    template:
      metadata:
        labels:
          app: will_app
      spec:
        containers:
        - name: will-playground
          image: wil42/playground:v2
          ports:
            - containerPort: 8888