apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: will-playground
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 8888
      protocol: TCP
  selector:
    app: will_app